FROM node:18-alpine

WORKDIR /backend

COPY package*.json ./

# Standard install for backend
RUN npm install && npm cache clean --force
# Create uploads directory
RUN mkdir -p uploads && chmod 777 uploads

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]